### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by weinierfei** [HujiangTechnology/AspectJX-Demo#1]
环境:win7+studio2.1正式版+jdk1.8

jar::::C:\Users\GuoYongPing\.gradle\caches\modules-2\files-2.1\org.aspectj\aspectjrt\1.8.9\87372d9e2323313bec24b09a325bfea8ae0eb867\aspectjrt-1.8.9.jar
copy jar::::C:\Users\GuoYongPing\.gradle\caches\modules-2\files-2.1\org.aspectj\aspectjrt\1.8.9\87372d9e2323313bec24b09a325bfea8ae0eb867\aspectjrt-1.8.9.jar
jar::::C:\Users\GuoYongPing\.gradle\caches\modules-2\files-2.1\com.nostra13.universalimageloader\universal-image-loader\1.9.3\a85588bec3e2c4584d593d3f15df1677321bca72\universal-image-loader-1.9.3.jar
aspect-inpath:::C:\Users\GuoYongPing\.gradle\caches\modules-2\files-2.1\com.nostra13.universalimageloader\universal-image-loader\1.9.3\a85588bec3e2c4584d593d3f15df1677321bca72\universal-image-loader-1.9.3.jar
jar::::F:\Android Studio\Studio\gradle\m2repository\org\jetbrains\kotlin\kotlin-runtime\1.0.0\kotlin-runtime-1.0.0.jar
copy jar::::F:\Android Studio\Studio\gradle\m2repository\org\jetbrains\kotlin\kotlin-runtime\1.0.0\kotlin-runtime-1.0.0.jar
jar::::F:\Android Studio\Studio\gradle\m2repository\org\jetbrains\kotlin\kotlin-stdlib\1.0.0\kotlin-stdlib-1.0.0.jar
copy jar::::F:\Android Studio\Studio\gradle\m2repository\org\jetbrains\kotlin\kotlin-stdlib\1.0.0\kotlin-stdlib-1.0.0.jar
jar::::F:\AndroidSDK\extras\android\m2repository\com\android\support\support-annotations\22.0.0\support-annotations-22.0.0.jar
copy jar::::F:\AndroidSDK\extras\android\m2repository\com\android\support\support-annotations\22.0.0\support-annotations-22.0.0.jar
jar::::C:\Users\GuoYongPing\.gradle\caches\modules-2\files-2.1\org.tukaani\xz\1.5\9c64274b7dbb65288237216e3fae7877fd3f2bee\xz-1.5.jar
copy jar::::C:\Users\GuoYongPing\.gradle\caches\modules-2\files-2.1\org.tukaani\xz\1.5\9c64274b7dbb65288237216e3fae7877fd3f2bee\xz-1.5.jar
jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\jars\classes.jar
copy jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\jars\classes.jar
jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\jars\classes.jar
copy jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\jars\classes.jar
jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\support-v4\22.0.0\jars\classes.jar
copy jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\support-v4\22.0.0\jars\classes.jar
jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\support-v4\22.0.0\jars\libs\internal_impl-22.0.0.jar
copy jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\com.android.support\support-v4\22.0.0\jars\libs\internal_impl-22.0.0.jar
jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\AspectJX-Demo\library\unspecified\jars\classes.jar
copy jar::::D:\ideaproject\AspectJX-Demo\app\build\intermediates\exploded-aar\AspectJX-Demo\library\unspecified\jars\classes.jar
file:::D:\ideaproject\AspectJX-Demo\app\build\intermediates\classes\debug
:app:transformClassesWithAspectTransformForDebug spend 784ms
:app:transformClassesWithExtractJarsForDebug FAILED
:app:transformClassesWithExtractJarsForDebug spend 21ms
Error:Execution failed for task ':app:transformClassesWithExtractJarsForDebug'.
> error

**Comment by weinierfei** [comment]
gradle插件版本写成2.1.0的时候,就会运行错误

**Comment by firefly1126** [comment]
这个是Instant Run 的一个Bug，可以在设置里关闭Instant Run功能解决。
见 https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/2

而且这种下直接Terminal命令编译是没有问题的。
