### ISSUE TITLE
第三方依赖引起的项目无法通过编译

### ISSUE THREAD

**Issue by weinierfei** [HujiangTechnology/AspectJX-Demo#2]
如果项目中有com.jakewharton:butterknife:7.0.1、httpmime（org.apache.httpcomponents:httpmime:4.5.2）的依赖后；项目编译通不过了
----------------------------------------------------------------------------------------------------------------------------

file:::E:\studioproject\tools\AspectJX-Demo\app\build\intermediates\classes\debug
can't determine implemented interfaces of missing type org.apache.http.HttpEntity
when weaving type org.apache.http.entity.mime.MultipartEntity
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType]
:app:transformClassesWithAspectTransformForDebug FAILED
:app:transformClassesWithAspectTransformForDebug spend 9599ms
Error:Execution failed for task ':app:transformClassesWithAspectTransformForDebug'.
> can't determine implemented interfaces of missing type org.apache.http.HttpEntity
when weaving type org.apache.http.entity.mime.MultipartEntity
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType]
Information:BUILD FAILED

**Comment by firefly1126** [comment]
找不到类org.apache.http.HttpEntity, aspectjx在扫描代码织入时会便利所有依赖关系，如果找不到依赖的类，就会出现上面这种情况，一种解决办法是导入依赖解决找不到依赖库的问题，另一种办法是加过滤配置aspectjx{jarFilter xxx, xxx},只加入你需要织入代码的库，其他库会忽略。后续版本会加入include， exclude功能，让依赖问题更方便解决。

**Comment by weinierfei** [comment]
![Uploading image.png…]()
window上过滤路径写错引起的错误

**Comment by koukoucai** [comment]
从com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.8  升到

**Comment by koukoucai** [comment]
从 com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.8 升到com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.10 后再加上   classpath 'org.aspectj:aspectjtools:1.8.9'
解决了我这aspectjx{
    includeJarFilter
   excludeJarFilter
}
不起作用的问题。
